# Starter pipeline

trigger: none

pool:
  vmImage: ubuntu-latest
steps:
  - task: DownloadBuildArtifacts@1
    inputs:
      buildType: 'specific'
      project: '957cd02c-b6d1-4cd9-a32a-eba3b0eb4e29'
      pipeline: '17'
      specificBuildWithTriggering: true
      buildVersionToDownload: 'latest'
      downloadType: 'single'
      artifactName: 'newmodel'
      downloadPath: '$(System.ArtifactsDirectory)'
  - task: AzureCLI@2
    inputs:
      azureSubscription: 'azure-resource-connection'
      scriptType: 'ps'
      scriptLocation: 'inlineScript'
      inlineScript: 'cat $(System.ArtifactsDirectory)/newmodel.txt'
