# Continuous Integration (CI) pipeline that orchestrates the training, evaluation, and registration of the AviationMLOps model.

resources:
  containers:
  - container: mlops
    image: mcr.microsoft.com/mlops/python:latest

pr: none
trigger:
  branches:
    include:
    - master
  paths:
    include:
    - AviationMLOps/
    - code/data_cycler.py
    - ./templates/data_cycler.yml

variables:
- group: devopsforai-aml-vg

pool:
  vmImage: ubuntu-latest

jobs:
- job: "Data_Cycling_Pipeline"
  displayName: "Data Cycling Pipeline"
  container: mlops
  timeoutInMinutes: 0
  steps:
  - template: templates/data_cycler.yml