# Continuous Integration (CI) pipeline that orchestrates the training, evaluation, and registration of the AviationMLOps model.

resources:
  containers:
  - container: mlops
    image: mcr.microsoft.com/mlops/python:latest

pr: none
trigger: none

variables:
- group: devopsforai-aml-vg

pool:
  vmImage: ubuntu-latest

jobs:
- job: "Training_Model_Pipeline"
  displayName: "Training and Registering Model Pipeline"
  container: mlops
  timeoutInMinutes: 0
  steps:
  - template: ./templates/train_register.yml

- job: "Training_Run_Report"
  dependsOn: "Run_ML_Pipeline"
  condition: always()
  displayName: "Publish artifact if new model was registered"
  container: mlops
  timeoutInMinutes: 0
  steps:
  - template: AviationMLOps-publish-model-artifact-template.yml
