# Continuous Integration (CI) pipeline that orchestrates the training, evaluation, and registration of the AviationMLOps model.

resources:
  containers:
  - container: mlops
    image: mcr.microsoft.com/mlops/python:latest

pr: none
trigger:
  branches:
    include:
    - master
  paths:
    include:
    - AviationMLOps/
    - code/train.py

variables:
- group: devopsforai-aml-vg

pool:
  vmImage: ubuntu-latest

jobs:
- job: "Training_Model_Pipeline"
  displayName: "Training and Registering Model Pipeline"
  container: mlops
  timeoutInMinutes: 0
  steps:
  - template: ./templates/train_register.yml